version: '3'

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    ports:
      - "28080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      - jenkins_network
    restart: always

networks:
  jenkins_network:
    name: jenkins-net
    external: true