version: '3'

services:
  jenkins:
    user: root
    privileged: true    
    # image: jenkins/jenkins
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "28080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # 这个是挂载宿主机的docker
      - /Users/zjzjzjzj1874/.kube:/root/.kube
    networks:
      - jenkins_network
    restart: always

networks:
  jenkins_network:
    name: jenkins-net
    external: true