version: '3.0'

networks:
  kms:
    external: true

services:
  access-rpc:
    env_file:
      - .env
    deploy: # cpu和内存限制
      resources:
        limits:
          cpus: '2'
          memory: 4000M
    image: ${HUB}access-rpc${TAG}
    container_name: access-rpc
    restart: always
    command: ./access -f /app/etc/access${BRANCH_ENV}.yaml
    privileged: true
    volumes:
      - ${KMS_PATH}/access/endpoint/rpc/etc:/app/etc
      - ${LOG_PATH}/logs/access:/app/logs
    ports:
      - "3200:3200"
    networks:
      - kms

  users-rpc:
    env_file:
      - .env
    image: ${HUB}users-rpc${TAG}
    container_name: users-rpc
    restart: always
    command: ./users -f /app/etc/users${BRANCH_ENV}.yaml
    privileged: true
    volumes:
      - ${KMS_PATH}/users/endpoint/rpc/etc:/app/etc
      - ${LOG_PATH}/logs/users-rpc:/app/logs
    networks:
      - kms
    ports:
      - "9001:9001"
    depends_on:
      - access-rpc

  access-api:
    env_file:
      - .env
    image: ${HUB}access-api${TAG}
    container_name: access-api
    restart: always
    command: ./access -f /app/etc/access-api${BRANCH_ENV}.yaml
    privileged: true
    volumes:
      - ${KMS_PATH}/access/endpoint/api/etc:/app/etc
      - ${LOG_PATH}/logs/access-api:/app/logs
    networks:
      - kms
    ports:
      - "8009:8009"
    depends_on:
      - access-rpc
      - users-rpc

  users-api:
    env_file:
      - .env
    image: ${HUB}users-api${TAG}
    container_name: users-api
    restart: always
    command: ./users -f /app/etc/users-api${BRANCH_ENV}.yaml
    privileged: true
    volumes:
      - ${KMS_PATH}/users/endpoint/api/etc:/app/etc
      - ${LOG_PATH}/logs/users-api:/app/logs
    networks:
      - kms
    ports:
      - "8001:8001"
    depends_on:
      - access-rpc
      - users-rpc
