version: "3.1"

networks:
  zero_test:
    external: true
services:
  mysql:
    image: amd64/mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    networks:
      - zero_test
    ports:
      - "3307:3306"
    volumes:
      - /tmp/data/mysql/data:/var/lib/mysql
      - /tmp/data/logs/mysql:/logs