# filebeat采集核心配置
filebeat.inputs:
  - type: log
    enabled: true
    paths: # filebeat采集的日志路径
      - /var/log/*/*

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.template.enabled: false
setup.template.overwrite: true
setup.ilm.enabled: auto # 开启index lifecycle management
setup.ilm.rollover_alias: "filebeat-test-ilm" # 索引前缀
setup.ilm.pattern: "{now/d}" # 索引日期 => 不会每天创建索引
setup.ilm.policy_name: "filebeat"
setup.dashboards.index: "filebeat-*"
# 可以参考这个https://www.jianshu.com/p/cf33deaa8684
processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~
  - add_cloud_metadata: ~

# kibana地址
setup.kibana:
  host: "0.0.0.0:5601"
# es地址:主要用于数据回吐
output.elasticsearch:
  hosts: [ "0.0.0.0:9200" ]
  index: "filebeat-dev-%{+yyyy.MM.dd}" # 创建索引 ==> 注意:如果ilm开启了,这里的index将不在生效