# 单节点方式启动ES和KIBANA
version: '3.0'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    user: root
    privileged: true
    volumes:
      - /data/elk/es/data/:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    environment:
      - "discovery.type=single-node"
    networks:
      - elk
    logging:
      options:
        max-size: 100m

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.9.3
    depends_on: [ 'elasticsearch' ]
    volumes:
      - /data/elk/kibana:/usr/share/kibana/ # 挂载kibana的文件
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    ports:
      - "5601:5601"
    restart: always
    networks:
      - elk

networks:
  elk: