version: '2'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - '~/rabbitmq/data/:/var/lib/rabbitmq/'
    restart: always
    privileged: true
    environment:
      RABBITMQ_DEFAULT_VHOST: '/'
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'

#docker run --privileged=true \
#-id -p 5672:5672 -p 15672:15672 \
#--name rabbitmq-1 -v /opt/rabbitmq/data:/var/lib/rabbitmq  \
#--restart=always  -e RABBITMQ_DEFAULT_USER=admin1 -e RABBITMQ_DEFAULT_PASS=admin1 \
#rabbitmq:3.8-management


