version: '3.0'
services:
  jaeger-query:
    container_name: jaeger-query
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M
    image: jaegertracing/jaeger-query:1.42
    user: root
    privileged: true
    ports:
      - "16685:16685"
      - "16686:16686"
      - "16687:16687"
    volumes:
      - ./jaeger-conf.yaml:/etc/jaeger/jaeger.yaml # 暂时不得行,jaeger-query目前不支持在使用时登陆,只能后面空了使用openshift+sidecar看看能不能实现
    environment:
      - "SPAN_STORAGE_TYPE=elasticsearch"
      - "ES_SERVER_URLS=http://localhost:9200"
      - "ES_USERNAME=elastic"
      - "ES_PASSWORD=uIA2sOHYQvYfyUUgxr2R"
      - "ES_USE_ILM=true" # 下面三个是用ilm管理的,也可以不用
      - "ES_USE_ALIASES=true"
      - "ES_CREATE_INDEX_TEMPLATES=false"
    restart: always

# 启动命令: docker-compose -f all-in-one.yml up -d
# 单条命令启动: docker run -d --name=jaeger-query --link elasticsearch2 -p 16686:16686 -p 16687:16687 -e SPAN_STORAGE_TYPE=elasticsearch -e ES_SERVER_URLS=http://localhost:9200 jaegertracing/jaeger-query:1.42
