version: '3.0'
services:
  jaeger-collector:
    container_name: jaeger-collector
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M
    image: jaegertracing/jaeger-collector:1.42
    user: root
    privileged: true
    ports:
      - "9411:9411"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
    environment:
      - "SPAN_STORAGE_TYPE=elasticsearch"
      - "ES_SERVER_URLS=http://localhost:9200"
      - "ES_USERNAME=elastic"
      - "ES_PASSWORD=uIA2sOHYQvYfyUUgxr2R"
      ## --es.use-ilm
      #(experimental) Option to enable ILM for jaeger span & service indices. Use this option with es.use-aliases.
      # It requires an external component to create aliases before startup and then performing its management.
      #    ILM policy must be manually created in ES before startup. Supported only for elasticsearch version 7+.
    restart: always

# 启动命令: docker-compose -f all-in-one.yml up -d
# 单条命令启动方式:docker run -d --name=jaeger-collector  -p 9411:9411 -p 14250:14250 -p 14268:14268 -p 14269:14269 -e SPAN_STORAGE_TYPE=elasticsearch -e ES_SERVER_URLS=http://localhost:9200 jaegertracing/jaeger-collector:1.42