version: '3'

services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'http://localhost:13000'
      APP_SECRET: 'aL1pPi87Hjtr'
      DATABASE_URL: 'postgresql://rw_user:admin123@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
      MAIL_DRIVER: 'smtp'
      SMTP_HOST: 'changeme'
      SMTP_PORT: 587
      SMTP_USERNAME: 'trigger_sentmail'
      SMTP_PASSWORD: 'changeme'
      SMTP_SECURE: 'tls'
      MAIL_FROM_ADDRESS: 'noreply@qq.com'
      MAIL_FROM_NAME: 'changme'
    ports:
      - "13000:3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: rw_user
      POSTGRES_PASSWORD: admin123
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  docmost:
  db_data:
  redis_data: