# 通过docker-compose创建基础组件服务 etcd、redis和MongoDB
version: '3.0'

networks:
  kms:
    internal: true

services:
#  etcd:
#    image: docker.io/bitnami/etcd:3.5
#    container_name: etcd
#    ports:
#      - "2379:2379"
#      - "2380:2380"
#    environment:
#      - ALLOW_NONE_AUTHENTICATION=yes
#      - ETCD_ADVERTISE_CLIENT_URLS=http://10.9.155.101:2379
#    networks:
#      - kms
#    volumes:
#      - etcd_data:/bitnami/etcd
  mango:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - kms
    ports:
      - "27017:27017"
    volumes:
      - /Users/cy-zjzjzjzj/tools/mongo/data:/etc/mongo
  redis:
    image: redis
    container_name: redis
    networks:
      - kms
    ports:
      - "6379:6379"
    volumes:
      - /Users/cy-zjzjzjzj/tools/redis/data:/data # 映射数据目录
    #      - /root/docker/redis/conf:/etc/redis/redis.conf # 映射配置文件
    command: redis-server --requirepass 123456a
    privileged: true  #环境变量
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8


volumes:
  etcd_data:
    driver: local
