# 通过docker-compose创建基础组件服务 etcd、redis和MongoDB
version: '3.0'

services:
  etcd:
    image: docker.io/bitnami/etcd:3.5
    container_name: etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://192.168.0.1:2379
    volumes:
      - etcd_data:/bitnami/etcd
  mango:
    env_file:
      - .env
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27018:27017'
    volumes:
      - ${HOME}/tools/mongo/data:/etc/mongo
      - ${LOG_PATH}/logs/mnogo:/app/logs
  mysql:
    env_file:
      - .env
    image: amd64/mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - '3307:3306'
    volumes:
      - ${HOME}/tools/mysql/data:/var/lib/mysql
      - ${LOG_PATH}/logs/mysql:/logs
  redis:
    env_file:
      - .env
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ${HOME}/redis/data:/data # 映射数据目录
      - ${HOME}/redis/conf:/etc/redis/redis.conf # 映射配置文件
    command: redis-server --requirepass 123456a
    privileged: true  #环境变量
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - '~/rabbitmq/data/:/var/lib/rabbitmq/'
    restart: always
    privileged: true
    environment:
      RABBITMQ_DEFAULT_VHOST: '/'
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'


volumes:
  etcd_data:
    driver: local
