version: "3"

networks:
  docker:
    internal: true

services:
  redis-master:
    env_file:
      - .env
    image: redis:${tag}
    container_name: redis-master
    build:
      context: .
      dockerfile: Dockerfile.use
    ports:
      - "6380:6380"
    networks:
      - docker
    privileged: true
    environment:
      - TZ=Asia/Shanghai



