version: "3"

networks:
  kms:
    internal: true
    
services:
  redis-master:
    env_file:
      - .env
    image: redis:${tag}
    container_name: redis-master
    ports:
      - "6380:6380"
    networks:
      - kms
    privileged: true
    environment:
      - TZ=Asia/Shanghai



